version: '3.8'

services:
  whisperx-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisperx-api 
    ports:
      - "9000:8000"  
    env_file:
      - .env
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - shared-data:/shared 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu] 
volumes:
  shared-data:
    external: true