version: '3.8'

services:
  whisperx-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisperx-api
    # runtime: nvidia  
    ports:
      - "8000:8000"  
    env_file:
      - .env 
    # environment:
    #   - DEBIAN_FRONTEND=noninteractive 
    #   - TZ=Etc/UTC  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu] 